In [1]:
import torch

torch.__version__

'1.4.0'

### Datatypes

Lets begin by exploring pytorch datatypes

In [6]:
torch.get_default_dtype()

torch.float32

In [10]:
# torch.set_default_dtype(torch.int) # error
torch.set_default_dtype(torch.float64) # see pytorch.org/docs/stable/tensors
torch.get_default_dtype()

torch.float64

In [14]:
tensor_arr = torch.Tensor([[1,2,3], [4,5,6]]) # alias for torch.FloatTensor
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [15]:
torch.is_tensor(tensor_arr)

True

In [16]:
torch.numel(tensor_arr)

6

In [19]:
torch_uninit = torch.Tensor(2,2)
torch_uninit

tensor([[4.6635e-310, 6.9096e-310],
        [6.9096e-310, 6.9096e-310]])

In [21]:
torch_init = torch.rand(2,2)
torch_init

tensor([[0.5103, 0.5095],
        [0.3865, 0.5681]])

In [23]:
tensor_int = torch.tensor([5,3]).type(torch.IntTensor)
tensor_int ## NOTE: GPU needs different dtype here

tensor([5, 3], dtype=torch.int32)

In [25]:
# we also have torch.ShortTensor and torch.half datatypes
tensor_short = torch.ShortTensor([1.0,2.0,3.0])
tensor_float = torch.tensor([1.0,2.0,3.0]).type(torch.half)
tensor_float

<ipython-input-25-5e8e39d4dcf5>:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  tensor_short = torch.ShortTensor([1.0,2.0,3.0])


tensor([1., 2., 3.], dtype=torch.float16)

In [27]:
## tensor with filled values
tensor_fill = torch.full((2,6), fill_value=10)
tensor_fill

tensor([[10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10.]])

In [29]:
# We can create tensors like some other tensor
tensor_zeros = torch.zeros_like(tensor_fill) 
tensor_zeros

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [31]:
## Eye
tensor_eye = torch.eye(5)
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [32]:
## finding zero values
non_zero = torch.nonzero(tensor_eye)
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [43]:
## Sparse data
i = torch.tensor([[0,1,1],[2,2,1]])
v = torch.tensor([2,4,5], dtype=torch.float32)
sparse_tensor = torch.sparse_coo_tensor(i,v,[2,5])
sparse_tensor

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 1]]),
       values=tensor([2., 4., 5.]),
       size=(2, 5), nnz=3, dtype=torch.float32, layout=torch.sparse_coo)

### Operations

Basic tensor operations in pytorch

In [45]:
initial_tensor = torch.rand(2,3)
initial_tensor

tensor([[0.2153, 0.2612, 0.4006],
        [0.9884, 0.6461, 0.0616]])

In [47]:
initial_tensor.fill_(10) ## _ means inplace

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [49]:
new_tensor = initial_tensor.add(5)
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [51]:
initial_tensor

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [52]:
initial_tensor.add_(8)

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [53]:
new_tensor.sqrt_()

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

In [56]:
x = torch.linspace(start=.1, end=10.0, steps=15)
x

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [58]:
tensor_chunk = torch.chunk(x,3,0)
tensor_chunk

(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]),
 tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]),
 tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))

In [61]:
torch.cat((tensor_chunk[0], tensor_chunk[1], tensor_chunk[2]), 0) # 0 is the dimension

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [68]:
r = torch.rand(3,3).mul_(100).floor()
r

tensor([[67.,  9., 92.],
        [38., 16., 43.],
        [87.,  9.,  9.]])

In [69]:
r[0,1]

tensor(9.)

In [70]:
r.size()

torch.Size([3, 3])

In [74]:
r.view(9) # NOTE: same underlying memory on the view
r

tensor([[67.,  9., 92.],
        [38., 16., 43.],
        [87.,  9.,  9.]])

In [78]:
resize = r.view(9)
resize.size()

torch.Size([9])

In [79]:
resize.div_(100)
resize

tensor([0.6700, 0.0900, 0.9200, 0.3800, 0.1600, 0.4300, 0.8700, 0.0900, 0.0900])

In [81]:
r # same underlying memory!

tensor([[0.6700, 0.0900, 0.9200],
        [0.3800, 0.1600, 0.4300],
        [0.8700, 0.0900, 0.0900]])

In [82]:
r.shape

torch.Size([3, 3])

In [83]:
unsqueezed = torch.unsqueeze(r, 2)
unsqueezed

tensor([[[0.6700],
         [0.0900],
         [0.9200]],

        [[0.3800],
         [0.1600],
         [0.4300]],

        [[0.8700],
         [0.0900],
         [0.0900]]])

In [84]:
unsqueezed.shape

torch.Size([3, 3, 1])

In [85]:
initial_sensor

tensor([[0.1760, 0.9811, 0.7868],
        [0.3850, 0.9860, 0.4789]])

In [87]:
torch.transpose(initial_sensor, 0,1) #switching dimensions

tensor([[0.1760, 0.3850],
        [0.9811, 0.9860],
        [0.7868, 0.4789]])

In [93]:
### Etc, we pretty much have all numpy fun in pytorch.. clamp is great though!
#r.mul(100)
r.clamp(min=10, max=50)

tensor([[50., 10., 50.],
        [38., 16., 43.],
        [50., 10., 10.]])

### PyTorch and Numpy

Basically the difference between numpy and torch tensors is that the pytorch tensors can be executed on GPU

In [94]:
r = torch.rand(3,3).mul_(100).floor()
r

tensor([[24., 57., 36.],
        [63., 71.,  3.],
        [84., 42., 26.]])

In [97]:
r.numpy() # from pytorch to numpy NOTE: The numpy ndarray created and the pytorch tensor share the same memory!

array([[24., 57., 36.],
       [63., 71.,  3.],
       [84., 42., 26.]])

In [98]:
import numpy as np # lets go from numpy to pytorch

In [107]:
randarray_np = np.floor(np.multiply(np.random.rand(2,4), 100))
randarray_np

array([[65., 20., 61., 25.],
       [52., 78.,  7., 44.]])

In [109]:
torch.from_numpy(randarray_np) # Also share the same underlying memory!

tensor([[65., 20., 61., 25.],
        [52., 78.,  7., 44.]])

In [112]:
avoid_unecc_copy_from_np = torch.as_tensor(randarray_np)
copied_from_np = torch.tensor(randarray_np)
copied_from_np

tensor([[65., 20., 61., 25.],
        [52., 78.,  7., 44.]])

In [114]:
torch.cuda.is_available() # :(

False

In [115]:
torch.cuda

0