# Numpy Basics 1

Hello and welcome to this quick tut on numpy using ipython.  We will here go through some of the core and basic functionality of numpy before we move on to more advanced data science tuts.

Numpy is a core library for a lot of data science and python for science libraries and provides us with high performance arrays which are used for computation accross the pydata universe.  Numpy is therefore one of the fundamental building blocks of python for ml and data science and must be understood before moving on to mode advanced topics.

**Lets begin by creating a normal python list:**

In [3]:
my_list = [1,2,3]
print(my_list)

[1, 2, 3]


### 1 Importing numpy and casting our basic python list

In [6]:
import numpy as np

In [7]:
np.array(my_list)

array([1, 2, 3])

### 2 Creating a matrix (list of list) and casting it to np array

In [9]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]
print(my_mat)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 3 Creating arrays using numpy functionality
Lets start by looking at the following functions

In [16]:
np.arange(0,10, 2) # (start, stop, stepsize)

array([0, 2, 4, 6, 8])

In [17]:
np.zeros((5,5)) # matrix: ((rows, columns)) list: (len)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [18]:
np.ones(5) # same as zeros, but for ones

array([ 1.,  1.,  1.,  1.,  1.])

In [20]:
np.linspace(0,10,7) # 1 dim number evenly spaced points from start to stop : (start, stop and number)

array([  0.        ,   1.66666667,   3.33333333,   5.        ,
         6.66666667,   8.33333333,  10.        ])

In [23]:
np.eye(5) # identity matrix: (rows, cols), but usually just one arg for both row and cols due to application

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [29]:
np.random.rand(3, 5) # random array: row [, cols]

array([[ 0.53812299,  0.01784455,  0.06443633,  0.95082607,  0.48229403],
       [ 0.74934245,  0.64547305,  0.30435742,  0.29368288,  0.93856556],
       [ 0.53955399,  0.40500565,  0.37449321,  0.19671888,  0.82003799]])

In [32]:
np.random.randn(5, 2) # pick random numbers from a normal distribution(center around 0): row [, cols]

array([[ 0.5838222 , -1.3821269 ],
       [ 0.86610409,  0.08848772],
       [ 0.44116765,  1.56370792],
       [-2.41245827, -0.14897877],
       [ 0.12878266, -1.38680781]])

In [35]:
np.random.randint(1,100, 5) # Get random integer between start - stop: start, stop [, numints]

array([66,  5, 41, 59, 74])

### 4 Simple operations on arrays
Now we have seen how we can create some different arrays in numpy. Now we will look at how we can alter them or find information about them

In [39]:
arr = np.arange(0,25) # First create an array arr
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
randarr = np.random.randint(0,50,10)
randarr

array([ 7,  8,  0,  3, 35, 21, 41, 33, 14,  9])

In [44]:
# RESHAPE!
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [50]:
# Finding max and min value
print(randarr)
print("max value in randarray is %i, min value is %i" % (randarr.max(), randarr.min()))
# and index
print("index of max is %i - index of min is %i" % (randarr.argmax(), randarr.argmin()))

[ 7  8  0  3 35 21 41 33 14  9]
max value in randarray is 41, min value is 0
index of max is 6 - index of min is 2


In [58]:
# Getting the shape of array
print(np.shape(randarr))
print(randarr.shape)
randarr = randarr.reshape(5,2)
print(randarr.shape)

(10,)
(10,)
(5, 2)


In [60]:
# Getting the datatype
randarr.dtype

dtype('int64')

### Conclusion
This concludes the first numpy tutorial.  We have learned about numpy arrays and some simple functionality for us to work with them.  Next up we will go deeper into using numpy arrays for all kinds of crazy adventures