# Numpy indexing and selection

In this tutorial we will look into how to select elements or groups of elements form numpy arrays

**Lets begin by importing numpy and creating an array: **

In [1]:
import numpy as np

In [3]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 1. Selecting from single dimenstional arrays
Now that we have created our array, we will start by doing some basic ways we can select and edit this array. As we can see, this is pretty similar to how we do it normally in python


In [4]:
arr[3] # Selecting an element from the array

3

In [7]:
print(arr[1:5]) # Slicing between two indexes
print(arr[:5]) # Slicing from start till index
print(arr[1:8:2]) # Slicing with step

[1 2 3 4]
[0 1 2 3 4]
[1 3 5 7]


## 2. Broadcasting
Now that we have seen the similarities and the simplicity of working with the arrays, we will now look at broadcasting of the arrays

In [8]:
arr[:5] = 100 # Broadcasting
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr = np.arange(0,11) # Reset the array

In [10]:
slice_of_array = arr[:5]
slice_of_array

array([0, 1, 2, 3, 4])

In [11]:
slice_of_array[:] = 99 # Broadcasting the slice of array to be 99
slice_of_array

array([99, 99, 99, 99, 99])

In [13]:
## --- Now notice that this has been broadcast to the arr array
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [16]:
# This occurs due to that numpy will not create copies by default when setting arrays
# If one wants this, one must declare it explicitely
arr_copy = arr.copy()
arr_copy # If we now broadcast values to this copy, the original array wont be altered

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

## 3. Working with two dimensional arrays - matrixes

Now that we have looked at working with arrays, we will take a closer look at how matrixes work in numpy

### 3.1 Getting values from matrices

In [19]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])
arr_2d  # Display our matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
# Selecting elements using the double bracket notation
print("Lets grab our first value : %i" % arr_2d[0][0])
print("Grabbing the first row %s" % arr_2d[0])
print("Grabbing first element in 3rd row : %i" % arr_2d[2][1])

Lets grab our first value : 5
Grabbing the first row [ 5 10 15]
Grabbing first element in 3rd row : 40


In [25]:
# Selecting elements using the single bracket notation
print("2nd col in first row is %i" % arr_2d[0,1]) 
print("3rd col in 2nd row is %i" % arr_2d[1,2]) 

2nd col in first row is 10
3rd col in 2nd row is 30


### 3.2 Slicing matrices

Slicing matrices in just like slicing arrays, except we now work with rows and columns:

In [28]:
# Get the top right corner for example
arr_2d[:2,1:] # [row slice, col slice]

array([[10, 15],
       [25, 30]])

In [30]:
# Get lower left corner
arr_2d[1:, :2]

array([[20, 25],
       [35, 40]])

## Boolean operations

Now that we have looket at selection, broadcasting and matrix slicing, we will take a look at some boolean operations - Fun!

Boolean arrays are very handy with conditional selection in numpy - **Lets take a look by creating a bool array and selecting values from an array using this boolean array**

In [31]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
bool_array = arr > 5 # Simple comparison with broadcasting
bool_array

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True], dtype=bool)

In [36]:
arr[bool_array] # The fun of boolean arrays is that we can use them to select from other arrays

array([ 6,  7,  8,  9, 10])

In [39]:
# Actually we can boil this process down to one line of code
arr[arr>5]

array([ 6,  7,  8,  9, 10])