# Numpy operations

Till now we have looked at using numpy for creating arrays and working with numpy for selecting values from these arrays.  In this tutorial we will take a closer look at the built in functionalities in numpy for altering these arrays.  Specifically in this tutorial we will look at:

- Array with array or scalars
- Universal array functions

Using scalars means that instead of using functions or arrays in operations, we use numbers which scale or broadcast across arrays


**Lets begin by importing numpy and look at some basic operations using both arrays and scalars:**

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
# Arithmetics with arrays
print("Addition: %s " % (arr + arr))
print("Subtraction: %s " % (arr - arr))
print("Multiplication: %s " % (arr * arr))
print("Division: %s " % (arr / 2)) # Arrays are also valid here, but in this case we broadcas a value
print("Exponent: %s" % (arr**2))

Addition: [ 0  2  4  6  8 10 12 14 16 18 20] 
Subtraction: [0 0 0 0 0 0 0 0 0 0 0] 
Multiplication: [  0   1   4   9  16  25  36  49  64  81 100] 
Division: [ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5. ] 
Exponent: [  0   1   4   9  16  25  36  49  64  81 100]


In [11]:
# Note that numpy will in some cases not give errors, but warnings on invalid operations
arr/0

/home/peakbreaker/.local/lib/python3.5/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  
/home/peakbreaker/.local/lib/python3.5/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([ nan,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf])

## Universal array functions
UAF is essentially just math operations given by numpy we can use to broadcast through an entire array

These functions are referred to as universal functions or ufunc for reference

**Lets take a look at some common ones: **

In [17]:
print(np.sqrt(arr)) # Square of the array
print(np.exp(arr)) # Exponential value of the array
print(np.min(arr)) # Finding min value
print(arr.max()) # Finding max value

[ 0.          1.          1.41421356  1.73205081  2.          2.23606798
  2.44948974  2.64575131  2.82842712  3.          3.16227766]
[  1.00000000e+00   2.71828183e+00   7.38905610e+00   2.00855369e+01
   5.45981500e+01   1.48413159e+02   4.03428793e+02   1.09663316e+03
   2.98095799e+03   8.10308393e+03   2.20264658e+04]
0
10


In [19]:
# Trigonometric funcations
print(np.sin(arr))
print(np.cos(arr))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153]


In [20]:
# Logarithms
np.log(arr)

/home/peakbreaker/.local/lib/python3.5/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])